# Generated by Django 5.2.4 on 2026-02-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_customer_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommapp.vendor'),
        ),
    ]
