# Generated by Django 5.2.4 on 2026-02-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_product_vender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_user',
        ),
    ]
