# Generated by Django 5.2.4 on 2026-02-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_remove_cartitem_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.customer'),
        ),
    ]
