# Generated by Django 5.2.4 on 2026-03-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_order_customer_user_alter_cartitem_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_user',
        ),
    ]
