# Generated by Django 5.2.4 on 2026-03-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.customer'),
        ),
    ]
